[package]
name = "fractal-oxide"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29"
rayon = "1.10"
image = "0.25"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
num-complex = "0.4"
